### ISSUE TITLE
can not get stdout when perli is running

### ISSUE THREAD

**Issue by wsdjeg** [mklement0/perli#4]
same issue as https://github.com/neovim/neovim/issues/1592

as the NOTE of neovim's job saied:

```
  Note: Buffered stdout/stderr data which has not been flushed by the sender
  will not trigger the on_stdout/on_stderr callback (but if the process
  ends, the on_exit callback will be invoked).
        For example, "ruby -e" buffers output, so small strings will be
        buffered unless "auto-flushing" ($stdout.sync=true) is enabled. >
          function! Receive(job_id, data, event)
            echom printf('%s: %s',a:event,string(a:data))
          endfunction
          call jobstart(['ruby', '-e',
            \ '$stdout.sync = true; 5.times do sleep 1 and puts "Hello Ruby!" end'],
            \ {'on_stdout': 'Receive'})
```

how about enable stdout.sync in perli?

and I am not sure if this link will help:

https://stackoverflow.com/questions/27059238/how-to-sync-print-and-warn-statements-in-perl

in this link, follow snippet is used to flush stdout:

```
use IO::Handle;

STDOUT->autoflush();
STDERR->autoflush();
```

**Comment by wsdjeg** [comment]
wow, Thanks for quick fix.

**Comment by mklement0** [comment]
@wsdjeg: You're welcome, though note that I've just published another version, v0.1.4, which also auto-flushes _stderr_.

Please check if the fix is effective and let me know if it isn't.

**Comment by wsdjeg** [comment]
@mklement0 Ok, I will test it.

**Comment by wsdjeg** [comment]
![default](https://user-images.githubusercontent.com/13142418/52608335-90369d00-2eb4-11e9-9081-056fb192b700.png)


works well now, awesome work, thanks.

**Comment by mklement0** [comment]
Glad to hear it, @wsdjeg  - thanks for testing and letting me know.
