### ISSUE TITLE
ARGUMENT ERROR: Unexpected argument(s)

### ISSUE THREAD

**Issue by dmolesUC** [mklement0/perli#6]
I'm getting the following when I try to launch `perli` on macOS (installed via NPM), with `rlwrap` installed via Homebrew:

```
perli: ARGUMENT ERROR: Unexpected argument(s): --remember -f
/var/folders/mq/dw4wtwsn7dlb_q99_qcd9kdc0000gn/T/_4v7sszQoS perl -n -w -C
/var/folders/mq/dw4wtwsn7dlb_q99_qcd9kdc0000gn/T/tKZZieitU8
Use -h for help.
```

The `/var/folders/mq/dw4wtwsn7dlb_q99_qcd9kdc0000gn/T` is `$TMPDIR`.

This happens both with the system perl 5.18, and Homebrew's perl 5.32.

**Comment by mklement0** [comment]
`rlwrap` must have introduced a breaking change: after upgrading it from `0.43` to `0.45`, I see the symptom too (both on Catalina and Big Sur).

**Comment by mklement0** [comment]
The - obviously suboptimal - workaround for now is to uninstall `rlwrap` (which may not be an option if other utilities use it too).

**Comment by dmolesUC** [comment]
Weirdly, if I just invoke `rlwrap` directly, it seems to work:

```
$ rlwrap --remember -f /var/folders/mq/dw4wtwsn7dlb_q99_qcd9kdc0000gn/T/aGEow5TTYj perl -n -w -C /var/folders/mq/dw4wtwsn7dlb_q99_qcd9kdc0000gn/T/8LPxpRTbdK
# perli v0.1.4, using perl v5.32.1 - ? shows help
perli> print "Hello, world\n";
Hello, world
1
perli> 
```

**Comment by mklement0** [comment]
Curious indeed, @dmolesUC.

I've found a workaround, though, and if you upgrade to v0.1.5 (`npm install perli -g`) the problem should be fixed.

The short of it:

    # --ansi-colour-aware makes rlwrap ANSI-color-aware (so it doesn't get "confused" by colored prompts)
    #    !! Before v0.45, --ansi-colour-aware was ineffective and had NO option-argument.
    #    !! Starting in v0.45, it gained and optional argument, '!', to "bleach" (strip colors from) prompt strings.
    #    !! The implementation is ambiguous, because the optional argument is expected as a *separate* argument, but that is apparently internally compensated for
    #    !! However, when the short form, -A, is used - curiously *only when launched via Per's `exec`* - *not* passing this optional argument *breaks the invocation on v0.45*.
    #    !! Fortunately, using the long form, --ansi-colour-aware, prevents that.

**Comment by dmolesUC** [comment]
Nice work, thanks!

**Comment by mklement0** [comment]
My pleasure; thanks for reporting the issue and helping with troubleshooting.

**Comment by mklement0** [comment]
(I've also reported the issue in the `rlwrap` repo; even though we have a workaround, the owner may want to know, as others could be affected too: https://github.com/hanslub42/rlwrap/issues/121)
