### ISSUE TITLE
Trailing `1` printed at repl

### ISSUE THREAD

**Issue by smac89** [mklement0/perli#7]
Here is a sample run of perli:

```sh
~ via ⬢ v14.15.4 took 8m1s 
➜ perli
# perli v0.1.5, using perl v5.32.1 - ? shows help
say "Hello, World"
Hello, World
1
say "The meaning of life is " . (0x2A)
The meaning of life is 42
1
perli>
```

As you can see, after each statement, it prints the number `1`.

Using just `perl -e`, I don't get an extra `1` being printed.

```sh
~ via ⬢ v14.15.4 took 2m57s 
➜ perl -e 'use v5.10; say "Hello, World!"'
Hello, World!

```

I'm on Arch Linux, and installed `perli` from [AUR](https://aur.archlinux.org/packages/perli/)

**Comment by smac89** [comment]
Looks like a duplicate of https://github.com/mklement0/perli/issues/5

Is there no other way to fix this than to simply not use `print` or `say` in the repl?

**Comment by mklement0** [comment]
Yes, it's a duplicate.

_Not_ having to use an explicit output function (`say`, `printf`) to me is a great convenience feature - no extra ceremony is needed just to see the result of an expression - given that you're in a REPL, the desired to _print_ results is a given.

Another way of saying it:

Submitting `"Hello, World!"`  alone in `perli` is the equivalent of `perl -e 'use v5.10; say "Hello, World!"'`

Conversely, this implicit result-printing is also applied if you do use explicit output functions.

Why do you want to use an explicit output command such as `say`?

**Comment by smac89** [comment]
Yea that makes perfect sense. I was just used to the python's print function in the repl. In python, `print` doesn't return anything.

I'm learning perl, which is why I installed this repl. I'm still at the "print Hello world" stage, which is why I was trying to use `say` and `print`.

Thanks for the clarification
